library(DBI)
library(dplyr)


con3 <- dbConnect(odbc::odbc(), "repro_prod", timeout = 10)
con2 <- dbConnect(odbc::odbc(), "reproreplica", timeout = 10)


clieN <- dbGetQuery(con2,"
           SELECT C.CLICODIGO FROM CLIEN C
           INNER JOIN (SELECT CLICODIGO FROM ENDCLI WHERE ENDFAT='S' AND ZOCODIGO IN (20,21,22,23,24,25,28))A ON A.CLICODIGO=C.CLICODIGO
           WHERE CLICLIENTE='S'") 

inativos <- dbGetQuery(con2,"
SELECT DISTINCT SITCLI.CLICODIGO,SITCODIGO FROM SITCLI
INNER JOIN (SELECT DISTINCT SITCLI.CLICODIGO,MAX(SITDATA)ULTIMA FROM SITCLI
GROUP BY 1)A ON SITCLI.CLICODIGO=A.CLICODIGO AND A.ULTIMA=SITCLI.SITDATA 
INNER JOIN (SELECT DISTINCT SITCLI.CLICODIGO,SITDATA,MAX(SITSEQ)USEQ FROM SITCLI
GROUP BY 1,2)MSEQ ON A.CLICODIGO=MSEQ.CLICODIGO AND MSEQ.SITDATA=A.ULTIMA 
AND MSEQ.USEQ=SITCLI.SITSEQ WHERE SITCODIGO=4
")


cli <- anti_join(clien,inativos,by="CLICODIGO")

View(cli)

